CREATE SEQUENCE seq_run_log START WITH 1 INCREMENT BY 1 NOCACHE; 
CREATE SEQUENCE seq_posting_id START WITH 1 INCREMENT BY 1 NOCACHE; 
CREATE SEQUENCE seq_td_closure_id START WITH 1 INCREMENT BY 1 NOCACHE; 
CREATE SEQUENCE seq_txn START WITH 1 INCREMENT BY 1 NOCACHE;